###################  spring配置  ###################
spring:
  application:
    name: yyadmin
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


management:
  security:
    enabled: false #关掉安全认证
  context-path: /management #actuator的访问路径　

###################  数据库连接池配置  ###################
druid:
  pool:
    initialSize: 10
    maxActive: 100
    minIdle: 10

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/yonyou/yyadmin/**/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yonyou.yyadmin.system.entity;
  global-config:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    auto-set-db-type: true
     #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
