spring:
  #数据库配置信息
  datasource:
    url: jdbc:mysql://localhost:3306/yyadmin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  devtools:
    restart:
      #配置需要热部署的文件夹
      additional-paths: src/main/java
      additional-exclude: static/**,public/**


  logging:
    config: classpath:logback.xml
    level.*: debug
    path: D://DEV/logs

  #缓存配置信息
  redis:
  # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 0
server:
  port: 8089

